!#/bin/sh

wget http://www.hematologyatlas.com/maturseq/4.jpg
wget http://www.hematologyatlas.com/maturseq/5.jpg
wget http://www.hematologyatlas.com/maturseq/6.jpg
wget http://www.hematologyatlas.com/maturseq/7.jpg
wget http://www.hematologyatlas.com/maturseq/8.jpg
wget http://www.hematologyatlas.com/maturseq/9.jpg
wget http://www.hematologyatlas.com/maturseq/10.jpg
wget http://www.hematologyatlas.com/maturseq/11.jpg
wget http://www.hematologyatlas.com/maturseq/12.jpg
wget http://www.hematologyatlas.com/maturseq/13.jpg
wget http://www.hematologyatlas.com/maturseq/14.jpg
wget http://www.hematologyatlas.com/maturseq/15.jpg
wget http://www.hematologyatlas.com/maturseq/16.jpg
wget http://www.hematologyatlas.com/maturseq/17.jpg
wget http://www.hematologyatlas.com/maturseq/18.jpg
wget http://www.hematologyatlas.com/maturseq/19.jpg
wget http://www.hematologyatlas.com/maturseq/20.jpg
wget http://www.hematologyatlas.com/maturseq/21.jpg
wget http://www.hematologyatlas.com/maturseq/22.jpg
wget http://www.hematologyatlas.com/maturseq/23.jpg
wget http://www.hematologyatlas.com/maturseq/24.jpg
wget http://www.hematologyatlas.com/maturseq/25.jpg
wget http://www.hematologyatlas.com/maturseq/26.jpg
wget http://www.hematologyatlas.com/maturseq/27.jpg
wget http://www.hematologyatlas.com/maturseq/28.jpg
wget http://www.hematologyatlas.com/maturseq/29.jpg
wget http://www.hematologyatlas.com/maturseq/30.jpg
wget http://www.hematologyatlas.com/maturseq/31.jpg
wget http://www.hematologyatlas.com/maturseq/32.jpg
wget http://www.hematologyatlas.com/maturseq/33.jpg
wget http://www.hematologyatlas.com/maturseq/34.jpg
wget http://www.hematologyatlas.com/maturseq/35.jpg
wget http://www.hematologyatlas.com/maturseq/36.jpg
wget http://www.hematologyatlas.com/maturseq/37.jpg
wget http://www.hematologyatlas.com/maturseq/38.jpg
wget http://www.hematologyatlas.com/maturseq/39.jpg
wget http://www.hematologyatlas.com/maturseq/40.jpg
wget http://www.hematologyatlas.com/maturseq/41.jpg
wget http://www.hematologyatlas.com/maturseq/42.jpg
wget http://www.hematologyatlas.com/maturseq/43.jpg
wget http://www.hematologyatlas.com/maturseq/44.jpg
wget http://www.hematologyatlas.com/maturseq/45.jpg
wget http://www.hematologyatlas.com/maturseq/46.jpg
wget http://www.hematologyatlas.com/maturseq/47.jpg
wget http://www.hematologyatlas.com/maturseq/48.jpg